# Generated by Django 4.0.4 on 2022-05-10 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Common_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_address', models.CharField(max_length=255)),
                ('user_photo', models.CharField(blank=True, max_length=255)),
                ('user_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country_region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_cpf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('civil_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilStatUser', to='user.civil_stat')),
                ('common_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_user')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
            ],
        ),
        migrations.CreateModel(
            name='User_cpf_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentsInterests', to='user.segment')),
                ('user_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersInterests', to='user.user_cpf')),
            ],
        ),
        migrations.CreateModel(
            name='User_cnpj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255, unique=True)),
                ('fancy_name', models.CharField(max_length=255)),
                ('corporate_name', models.CharField(max_length=255)),
                ('common_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.common_user')),
                ('segments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companySegments', to='user.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Country_state',
            fields=[
                ('state_code', models.IntegerField(unique=True)),
                ('state_name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_region')),
            ],
        ),
        migrations.CreateModel(
            name='Country_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.IntegerField(unique=True)),
                ('city_name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_state')),
            ],
        ),
        migrations.AddField(
            model_name='common_user',
            name='user_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_city'),
        ),
    ]
