# Generated by Django 4.0.4 on 2022-05-27 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=255)),
                ('form_description', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('form_active', models.BooleanField(default=True)),
                ('user_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_cnpj')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255)),
                ('question_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=255)),
                ('type_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.TextField()),
                ('answer_date_creation', models.DateField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question')),
                ('user_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_cpf')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question_type'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
    ]
